version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: pishock
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"